# Generated by Django 5.2.16 on 2026-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=30)),
                ('fuel', models.CharField(max_length=30)),
                ('mileage', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
