# Generated by Django 5.2.16 on 2026-07-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'МКПП'), ('automatic', 'АКПП'), ('cvt', 'Вариатор'), ('robot', 'Робот')], max_length=20)),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('gas', 'Газ'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро')], max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('city', models.CharField(choices=[('astana', 'Астана'), ('almaty', 'Алматы'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('aktobe', 'Актобе'), ('atyrau', 'Атырау')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('engine', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand')),
            ],
        ),
    ]
