# Generated by Django 5.2.16 on 2026-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=3),
            preserve_default=False,
        ),
    ]
