# Generated by Django 5.2.16 on 2026-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
